recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('recipes/', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from .views import welcome, RecipeListView, RecipeDetailView, records

app_name = 'recipes'

urlpatterns = [
    path('', welcome, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', records, name='search'),
]

recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.


class Recipe (models.Model):
    name = models.CharField(max_length=120)
    cooking_time = models.FloatField(help_text='in minutes')
    ingredients = models.CharField(max_length=350)
    description = models.TextField()
    pic = models.ImageField(upload_to='recipes',
                            default='no-image-icon-23494.png')

    # calculate difficulty of recipe using cooking time and number of ingredients
    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 30 and len(ingredients) < 7:
            difficulty = 'Easy'
        elif self.cooking_time < 30 and len(ingredients) >= 7:
            difficulty = 'Medium'
        elif self.cooking_time >= 30 and len(ingredients) < 7:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 30 and len(ingredients) >= 7:
            difficulty = 'Hard'
        return difficulty

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk': self.pk})

recipes/forms.py
from django import forms

CHART__CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart')
)

DIFFICULTY__CHOICES = (
    ('#1', 'Easy'),
    ('#2', 'Medium'),
    ('#3', 'Intermediate'),
    ('#4', 'Hard')
)


class RecipeSearchForm(forms.Form):
    recipe_difficulty = forms.ChoiceField(choices=DIFFICULTY__CHOICES)
    chart_type = forms.ChoiceField(choices=CHART__CHOICES)

recipe_project/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm


def login_view(request):
    error_message = None

    form = AuthenticationForm()

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(username=username, password=password)
            if user is not None:

                login(request, user)
                return redirect('/list')

        else:
            error_message = 'oops...something went wrong'

    context = {
        'form': form,
        'error__message': error_message
    }
    return render(request, 'auth/login.html', context)


def logout_view(request):
    logout(request)
    return render(request, 'auth/success.html')

recipes/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipeSearchForm
import pandas as pd
from .utils import get_recipename_from_id, get_chart

# Create your views here.


def welcome(request):
    return render(request, 'recipes/recipes_home.html')


class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipes_list.html'


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'


@login_required
def records(request):
    form = RecipeSearchForm(request.POST or None)
    recipe_df = None
    recipe_difficulty = None
    chart = None
    qs = None

    if request.method == 'POST':
        recipe_difficulty = request.POST.get('recipe_difficulty')
        chart_type = request.POST.get('chart_type')

        if recipe_difficulty == '#1':
            recipe_difficulty = 'Easy'
        if recipe_difficulty == '#2':
            recipe_difficulty = 'Medium'
        if recipe_difficulty == '#3':
            recipe_difficulty = 'Intermediate'
        if recipe_difficulty == '#4':
            recipe_difficulty = 'Hard'

        qs = Recipe.objects.all()
        id_searched = []
        for obj in qs:
            difficulty = obj.calculate_difficulty()
            if difficulty == recipe_difficulty:
                id_searched.append(obj.id)

        qs = qs.filter(id__in=id_searched)

        if qs:
            recipe_df = pd.DataFrame(qs.values())
            chart = get_chart(chart_type, recipe_df,
                              labels=recipe_df['name'].values)

            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipe_difficulty': recipe_difficulty,
        'chart': chart,
        'qs': qs
    }

    return render(request, 'recipes/search.html', context)

recipes/templates/recipes/detail.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head> 
  <title>Recipe App Details</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<div class="details_modal">
  <h2>Details: {{object.name}}</h2>
  <div class="details_body">
    <div class="details_short">
      <b>Name: </b> {{object.name}} <br>
      <b>Cooking Time (in min): </b> {{object.cooking_time}} <br>
      <b>Difficulty: </b> {{object.calculate_difficulty}} <br><br>
      <img class="recipe_images" src="{{object.pic.url}}" />
    </div>
    <div class="details_long">
      <b>Ingredients: </b> {{object.ingredients}}<br><br>
      <b>Description: </b> {{object.description}}<br><br>
      <button onclick="goBack()" class="login_btn">Back</button>
    </div>
  </div>
</div>
<script>
  function goBack(){
    window.history.back();
  }
</script>

</html>

recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>
        Recipe-App Home
      </title>
    <meta name="viewport" content="width=device-width, inital-scale=1">
  {% load static %}
  
    <style type="text/css">
    body {
      background: url("{% static 'recipes/images/recipe_welcome.jpeg' %}") no-repeat fixed;
      background-size: cover;
      display: flex;
      flex-direction: column;
      align-items: center;
      margin-top: 30vh;
    }

    h1,
    h3 {
      color: rgb(7, 120, 90);
      font-family: 'Roboto Mono', 'Calibri', 'Trebuchet MS', sans serif;
    }
      img {
      border-radius: 15px;
    }

    </style>
  </head>
  

<body>
    <h1 style="text-align:center">Welcome to the Recipe App</h1> 
    <h3>Log in for list of recipes</h3>
    <a href="{%url 'login' %}" class="login_btn">Login</a>  
</body>

</html>

recipes/templates/recipes/recipes_list.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Recipes</title>
  <meta name="viewport" content="width=device-width, intial-scale=1">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/styles.css' %}">
</head>

<body>
  <div class="nav-bar">
    <div class="search-box">
      <form action="" method="GET" class="form">
        {% csrf_token %}
        <input type="text" name="recipe_search" class="form_search_input" id="searchbar"
            placeholder="Search Recipes" onkeyup="search_recipe()" />
      </form>
      <br>
      <div class="search_results" autocomplete="off" style="display:none;">
            {% for object in object_list %}
            <p class="recipe_searched">
              <a class="recipe_name"
                  style="font-size: 18px; font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
                  href="{{object.get_absolute_url}}"> {{object.name}} </a>
                </p>
                {% endfor %}
      </div>
    </div>
    <div>
      <a href="{%url 'recipes:search' %}" class="logout_btn">Display Recipe Data </a>
    </div>
    <br>
    <br>
    <div>
      <a href="{%url 'logout' %}" class="logout_btn">Logout</a>
    </div>
  </div>
  <div class="recipe_grid">
    {% for object in object_list %}
    <div class="grid_item">
      <h4><a class="recipe_name" href="{{object.get_absolute_url}}"> {{object.name}} </a></h4>
      <div style="margin-bottom: 10px;">
            <b>Cooking Time: </b> {{object.cooking_time}} <br>
            <b>Difficulty: </b> {{object.calculate_difficulty}} <br>
      </div>
      <img class="recipe_images" src="{{object.pic.url}}" />
    </div>
    {% endfor %}
  </div>
  <script src="{% static 'recipes/js.js' %}"></script>
</body>

</html>

recipes/templates/recipes/search.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>RecipeApp Search</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/styles.css' %}">
  <style type="text/css">
    body {
      background: url("{% static 'recipes/images/recipe_welcome.jpeg' %}") no-repeat fixed;
            background-size: cover;
            color: black;
            display: flex;
            flex-direction: column;
            align-items: center;
            font-family: 'Roboto Mono', 'Calibri', 'Trebuchet MS', sans-serif;
        }

        .form_data {
            background-color: rgba(0, 0, 0, 0.61);
            border-radius: 10px;
            padding: 20px;
        }
  </style>
</head>

<h1>Search for recipes</h1>

<hr>
<form action="" method="POST" class="form_data">
  {% csrf_token %}
  {{form}}
  <button type="submit">Search</button>
</form>
<br>
<br>
{% if recipe_df %}
{{recipe_df|safe}}
<br>
<img src="data:image/png;base64, {{chart|safe}}">
{% else %}
<h3> no data </h3>
{% endif %}
<br>
<button onclick="goBack()" class="login_btn">Back</button>

<script>
    function goBack() {
        window.history.back();
    }
</script>

</html>